### ISSUE TITLE
Read documentation about CI CD

### ISSUE THREAD

**Issue by berkaydemirtas** [bounswe/2021SpringGroup10#139]
Project will be deployed to aws. Before the meeting (12.11.2021) check the documentation below.
https://aws.amazon.com/blogs/containers/create-a-ci-cd-pipeline-for-amazon-ecs-with-github-actions-and-aws-codebuild-tests/

**Comment by OnurSefa** [comment]
This issue will be suspended until we fully understand the implementation using AWS.

**Comment by OnurSefa** [comment]
I close this issue, because we managed to handle operations until now and could not find a time window where we can implement CI CD property. Also, because there is little time to end this project, it is unneccessary to implement this technique. If we implement it, all the endpoints will be transfered and te produced workload will be higher than the current.
