### ISSUE TITLE
Mongo Database Accepts Not Intended Fields

### ISSUE THREAD

**Issue by ekingungor** [bounswe/2021SpringGroup10#143]
While @berkaydemirtas  and I test the `/api/profile_page/` endpoint we have tried the following request:

TO: `/api/profile_page/` endpoint
``
{
"user_name": "eking",
"sjdjfs":"hello"
}
``

and we have seen that `sjdjfs`field is also saved to the database.

We can prevent this from happening in the code by always checking (and excluding) the given arguments OR the database could actively prevent this from happening by expecting only a set of defined fields.

I would prefer the latter one if possible, because the former might be ugly. @OnurSefa can we enforce this in the database and which solution would you prefer?

**Comment by OnurSefa** [comment]
Because of the property of object type database system used by MongoDB, we can not define a method in which MongoDB choose only necessary parts of the input regardless of whatever we send. So, second option is not possible as far as I know. First option seems not ugly for me. We don't have check explicitly but we can arrange the insertion code to prevent this behaviour.

**Comment by OnurSefa** [comment]
The problem solved using the methodology mentioned previously.

> Because of the property of object type database system used by MongoDB, we can not define a method in which MongoDB choose only necessary parts of the input regardless of whatever we send. So, second option is not possible as far as I know. First option seems not ugly for me. We don't have check explicitly but we can arrange the insertion code to prevent this behaviour.
