### ISSUE TITLE
Creating a flask example

### ISSUE THREAD

**Issue by fleafclover** [bounswe/2021SpringGroup10#59]
create a simple flask example project to help team members to learn flask. This project should contain get and post methods and db connection (mongoDb).

**Comment by OnurSefa** [comment]
First I should learn mongoDB. Fortunately they offere very clean [documentation](https://docs.mongodb.com/). Also they offer tutorials, examples, and practices.

**Comment by OnurSefa** [comment]
Regarding to my research I have created two example apps. [Flask-Example](https://github.com/Gepsmin/Flask_Example) is more simple one but it still uses mongoDB. It mostly offers a playground. [Flask-Spotify-Example](https://github.com/Gepsmin/Flask_Spotify_Example) is more complex and for who wants to play with more complex APIs. Because of that I also didn't finish this example completely. I have shared them with my teammates.
