### ISSUE TITLE
Give Recommended Resources about Unit Test implementation on Python, Flask

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#77]
I am confused about how to use unit tests in our project. Giving resources like examples and documentations would help me and our teammates who may struggle.

**Comment by ekingungor** [comment]
@OnurSefa, since we are using the Flask framework, you can directly use this library, [flask-unittest 0.1.1 library ](https://pypi.org/project/flask-unittest/), which provides utilities for flask application testing. In this page, it is also recommended to somewhat learn about the [ official flask application testing guidelines](https://flask.palletsprojects.com/en/1.1.x/testing/). However I think we don't need that much knowledge right now, you can just use the utilities provided by [flask-unittest 0.1.1 library ](https://pypi.org/project/flask-unittest/).

**Comment by safaaltunel** [comment]
> @OnurSefa, since we are using the Flask framework, you can directly use this library, [flask-unittest 0.1.1 library ](https://pypi.org/project/flask-unittest/), which provides utilities for flask application testing. In this page, it is also recommended to somewhat learn about the [ official flask application testing guidelines](https://flask.palletsprojects.com/en/1.1.x/testing/). However I think we don't need that much knowledge right now, you can just use the utilities provided by [flask-unittest 0.1.1 library ](https://pypi.org/project/flask-unittest/).

Thanks, mate. It helped me really much. I've used unittest library and usage of it is a piece of cake!
